holder_12_0 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[1]/a/font/text()")
holder_12_1 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[1]/a/text()")
holder_12_2 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[2]/a/font/text()")
holder_12_3 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[2]/a/text()")
holder_12_4 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[3]/a/font/text()")
holder_12_5 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[3]/a/text()")
holder_12_6 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[4]/a/font/text()")
holder_12_7 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[4]/a/text()")
holder_12_8 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[5]/a/font/text()")
holder_12_9 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[5]/a/text()")
holder_12_10 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[6]/a/font/text()")
holder_12_11 = page_source.xpath(
    "//*[@id='search_result_former']/div[4]/div[1]/ul/li[12]/div/div[2]/div/p[6]/span[6]/a/text()")
holder_12 = holder_12_0 + holder_12_1 + holder_12_2 + holder_12_3 + holder_12_4 + holder_12_5 + holder_12_6 + holder_12_7 + holder_12_8 + holder_12_9 + holder_12_10 + holder_12_11
